# Generated by Django 6.0.4 on 2026-04-15 19:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioEncFija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Form Encuesta Fija',
                'verbose_name_plural': 'Form Encuestas Fijas',
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_de_opcion', models.CharField(max_length=255)),
                ('valor_numerico', models.DecimalField(decimal_places=0, default=1, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('tipo_de_pregunta', models.CharField(choices=[('texto', 'Texto'), ('numerico', 'Numérico'), ('seleccion_simple', 'Selección Simple')], max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='premios/', verbose_name='Imagen del Producto')),
            ],
            options={
                'verbose_name': 'Premio',
                'verbose_name_plural': 'Premios',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regiones', to='encuestas.pais')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.CreateModel(
            name='EncuestaFija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('tipo_juego', models.CharField(choices=[('RULETA', 'Ruleta de Premios'), ('CAJAS', 'Cajas de Regalos')], default='RULETA', max_length=10, verbose_name='Tipo de Juego Post-Encuesta')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('encabezado', models.TextField(blank=True, verbose_name='Text de encabezado de ticket')),
                ('texto', models.TextField(blank=True, verbose_name='Text de pie de página de ticket')),
                ('encuestafija', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuestasfijas', to='encuestas.formularioencfija', verbose_name='Encuesta Fija')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuestasfijas', to='encuestas.pais')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuestasfijas', to='encuestas.region')),
            ],
            options={
                'verbose_name': 'Encuesta Fija',
                'verbose_name_plural': 'Encuestas Fijas',
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to='encuestas.pais')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to='encuestas.region')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('activa', models.BooleanField(default=True)),
                ('id_efsystem', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('monto_minimo_promociones', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto mínimo para habilitar promociones')),
                ('requiere_validacion_ticket', models.BooleanField(default=False, help_text='Marcar si esta tienda (ej. Tienda Online) debe validar el ticket contra la tabla de Ventas en Línea.', verbose_name='¿Requiere validación de ticket online?')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiendas', to='encuestas.pais')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiendas', to='encuestas.region')),
            ],
        ),
        migrations.CreateModel(
            name='TicketVentasEnLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_ticket', models.CharField(help_text='El código único que se le da al cliente.', max_length=50, unique=True, verbose_name='Número de Ticket')),
                ('utilizado', models.BooleanField(default=False, help_text='Se marca automáticamente cuando el cliente completa la encuesta.', verbose_name='¿Ya fue utilizado?')),
                ('vigencia', models.DateTimeField(help_text='Fecha y hora en que el ticket expira.', verbose_name='Válido hasta')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('encuesta_fija', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_online', to='encuestas.encuestafija', verbose_name='Encuesta a aplicar')),
                ('tienda', models.ForeignKey(help_text='La tienda online a la que pertenece este ticket.', on_delete=django.db.models.deletion.CASCADE, to='encuestas.tienda')),
            ],
            options={
                'verbose_name': 'Ticket de Venta en Línea',
                'verbose_name_plural': 'Tickets de Venta en Línea',
            },
        ),
        migrations.CreateModel(
            name='TicketConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ticket', models.CharField(max_length=255)),
                ('texto_de_respuesta', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='encuestas.encuesta')),
                ('opcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='encuestas.opcion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='encuestas.pregunta')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='encuestas.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaFijaRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=9)),
                ('codigo_ticket', models.CharField(max_length=255, null=True)),
                ('fnac', models.DateField()),
                ('correo', models.EmailField(max_length=254)),
                ('DNI', models.CharField(max_length=9)),
                ('acepPolPriv', models.BooleanField()),
                ('acepProm', models.BooleanField(blank=True, null=True)),
                ('fecha_respuesta', models.DateField(default=datetime.date.today)),
                ('valoracion_producto', models.IntegerField(default=0, verbose_name='Valoración del producto')),
                ('valoracion_atencion', models.IntegerField(default=0, verbose_name='Valoración de la atención')),
                ('probabilidad_recomendacion', models.IntegerField(default=0, verbose_name='Probabilidad de recomendación')),
                ('comentarios_adicionales', models.TextField(blank=True, null=True, verbose_name='Comentarios adicionales')),
                ('calificacion', models.IntegerField(blank=True, default=0, null=True)),
                ('pregunta_1_1', models.CharField(blank=True, max_length=255, null=True)),
                ('pregunta_1_2', models.TextField(blank=True, null=True)),
                ('pregunta_2_1', models.CharField(blank=True, max_length=255, null=True)),
                ('pregunta_2_2', models.TextField(blank=True, null=True)),
                ('pregunta_3_1', models.CharField(blank=True, max_length=255, null=True)),
                ('encuesta_fija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='encuestas.encuestafija')),
                ('tienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_encuesta', to='encuestas.tienda')),
            ],
            options={
                'verbose_name': 'Respuesta de Encuesta Fija',
                'verbose_name_plural': 'Respuestas de Encuesta Fija',
            },
        ),
        migrations.CreateModel(
            name='EncuestaFijaPremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('codigo_ticket', models.CharField(max_length=255, null=True)),
                ('DNI', models.CharField(max_length=9)),
                ('fecha_respuesta', models.DateField(default=datetime.date.today)),
                ('encuesta_fija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios_entregados', to='encuestas.encuestafija')),
                ('respuesta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premios', to='encuestas.encuestafijarespuesta')),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios_entregados', to='encuestas.premio')),
                ('tienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premios_entregados', to='encuestas.tienda')),
            ],
            options={
                'verbose_name': 'Premio de Encuesta Fija',
                'verbose_name_plural': 'Premios de Encuesta Fija',
            },
        ),
        migrations.AddField(
            model_name='encuestafija',
            name='tiendas',
            field=models.ManyToManyField(blank=True, related_name='encuestasfijas', to='encuestas.tienda'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='tiendas',
            field=models.ManyToManyField(blank=True, related_name='encuestas', to='encuestas.tienda'),
        ),
        migrations.CreateModel(
            name='EncuestaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta_preguntas', to='encuestas.encuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to='encuestas.pregunta')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('encuesta', 'pregunta')},
            },
        ),
        migrations.CreateModel(
            name='PreguntaOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_opciones', to='encuestas.opcion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_opciones', to='encuestas.pregunta')),
            ],
            options={
                'verbose_name': 'Opción de Pregunta',
                'verbose_name_plural': 'Opciones de Preguntas',
                'ordering': ['orden'],
                'unique_together': {('pregunta', 'opcion')},
            },
        ),
        migrations.CreateModel(
            name='TiendaPremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('monto_minimo_premio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto mínimo para premio')),
                ('visible', models.BooleanField(default=False, verbose_name='Visible en lista de premios')),
                ('orden', models.PositiveIntegerField(db_index=True, default=0)),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios_tienda', to='encuestas.premio')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tienda_premios', to='encuestas.tienda')),
            ],
            options={
                'verbose_name': 'Premio de tienda',
                'verbose_name_plural': 'Premios de tienda',
                'ordering': ['orden'],
                'unique_together': {('tienda', 'premio')},
            },
        ),
    ]
