# Generated by Django 6.0.4 on 2026-04-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premio',
            name='es_premio',
            field=models.BooleanField(default=True, verbose_name='¿Es un premio real?'),
        ),
        migrations.AddField(
            model_name='tiendapremio',
            name='fecha_activacion',
            field=models.DateField(blank=True, help_text='El premio no saldrá sorteado antes de esta fecha.', null=True, verbose_name='Activo desde'),
        ),
    ]
